//
// Autogenerated by Thrift Compiler (0.21.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

import thrift from 'thrift';
var Thrift = thrift.Thrift;
var Q = thrift.Q;
import Int64 from 'node-int64';


import ttypes from './api_types';
//HELPER FUNCTIONS AND STRUCTURES

class APIService_GetData_args {
  constructor(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined && args.request !== null) {
      this.request = new ttypes.GetDataRequest(args.request);
    }
  }
}
}
APIService_GetData_args.prototype = {};
APIService_GetData_args.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.GetDataRequest();
        this.request[Symbol.for("read")](input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APIService_GetData_args.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('APIService_GetData_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

class APIService_GetData_result {
  constructor(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.GetDataResponse(args.success);
    }
  }
}
}
APIService_GetData_result.prototype = {};
APIService_GetData_result.prototype[Symbol.for("read")] = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GetDataResponse();
        this.success[Symbol.for("read")](input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

APIService_GetData_result.prototype[Symbol.for("write")] = function(output) {
  output.writeStructBegin('APIService_GetData_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success[Symbol.for("write")](output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var APIServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
APIServiceClient.prototype = {};
class APIServiceClient {
  seqid() { return this._seqid; }
};
class APIServiceClient {
  new_seqid() { return this._seqid += 1; }
};

class APIServiceClient {
  GetData(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      }
} else {
        _defer.resolve(result);
      }
    };
    this.send_GetData(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetData(request);
  }
};

class APIServiceClient {
  send_GetData(request) {
  var output = new this.pClass(this.output);
  var params = {
    request: request
  }
};
  var args = new APIService_GetData_args(params);
  try {
    output.writeMessageBegin('GetData', Thrift.MessageType.CALL, this.seqid());
    args[Symbol.for("write")](output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

class APIServiceClient {
  recv_GetData(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {}
};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x[Symbol.for("read")](input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new APIService_GetData_result();
  result[Symbol.for("read")](input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetData failed: unknown result');
};
var APIServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
class APIServiceProcessor {
  process(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  }
} else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x[Symbol.for("write")](output);
    output.writeMessageEnd();
    output.flush();
  }
};
class APIServiceProcessor {
  process_GetData(seqid, input, output) {
  var args = new APIService_GetData_args();
  args[Symbol.for("read")](input);
  input.readMessageEnd();
  if (this._handler.GetData.length === 1) {
    Q.fcall(this._handler.GetData.bind(this._handler),
      args.request
    ).then(function(result) {
      var result_obj = new APIService_GetData_result({success: result}
});
      output.writeMessageBegin("GetData", Thrift.MessageType.REPLY, seqid);
      result_obj[Symbol.for("write")](output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("GetData", Thrift.MessageType.EXCEPTION, seqid);
      result[Symbol.for("write")](output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.GetData(args.request, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new APIService_GetData_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("GetData", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetData", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj[Symbol.for("write")](output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
