//
// Autogenerated by Thrift Compiler (0.21.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import Int64 = require('node-int64');


export declare class GetDataRequest {
  ID: string;

    constructor(args?: { ID: string; });
}

export declare class GetDataResponse {
  data: string;
  success: boolean;
  errorMessage?: string;

    constructor(args?: { data: string; success: boolean; errorMessage?: string; });
}
